name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cancel_previous:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          workflow_id: ${{ github.event.workflow.id }}

  generate_code_coverage:
    needs: cancel_previous
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"
      - uses: actions/checkout@v2
      - name: Build & Run tests
        run: swift test --enable-code-coverage
      - name: Convert coverage report
        run: xcrun llvm-cov export -format="lcov" .build/debug/SubstrataPackageTests.xctest/Contents/MacOS/SubstrataPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: segment-integrations/substrata-swift

  build_and_test_spm_mac:
    needs: cancel_previous
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"
      - uses: actions/checkout@v2
      - name: Build & Run tests
        run: swift test

  build_and_test_ios:
    needs: cancel_previous
    runs-on: macos-15
    steps:
      - name: Install yeetd
        run: |
          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
          sudo installer -pkg yeetd-normal.pkg -target /
          yeetd &
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"
      - uses: actions/checkout@v2
      - run: xcodebuild -scheme Substrata-Package test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16'
# disabled for tvOS -- unable to build right now.
#
#
#	'execve' is unavailable: not available on tvOS
#	'execve' is unavailable: not available on tvOS
#	'fork' is unavailable: not available on tvOS
#	'execve' is unavailable: not available on tvOS
#
#  build_and_test_tvos:
#    needs: cancel_previous
#    runs-on: macos-15
#    steps:
#      - uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: "16.2"
#      - uses: actions/checkout@v2
#      - run: xcodebuild -scheme Substrata-Package test -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV'
